"fuse_diam"= 10
"fuse_rad"= "fuse_diam" / 2
"fuse_length"= 25
"wing_rotation_hor"= 0.1 * "fuse_length"
"D1@Sketch1"="fuse_diam"
"D1@Fuselage" = "fuse_length"
"wing_rotation_vert"= 0.6 * "fuse_rad"
"D1@Sketch2"= "wing_rotation_vert"
"tail_length"= "fuse_length" * 1.5
"tail_diam"= 0.5 * "fuse_diam"
"tail_connector"= 10
"D1@Sketch3"="tail_diam"
"tail_elevation"= ( "fuse_diam" - "tail_diam" ) * 0.2
"D2@Sketch3"="tail_elevation"
"tri_length"= 1.5
"vtail_mount_anglet"= arccos ( ( ( "tail_rad" * "tail_rad" + "tail_rad" * "tail_rad" ) - ( "tri_length" * "tri_length" ) ) / ( 2 * "tail_rad" * "tail_rad" ) )
"tail_rad"= "tail_diam" / 2
"vtail_mount"= "tri_length" * sin ( ( 360 - ( 3 * "vtail_mount_anglet" ) ) / 3 ) * 2
"D3@Sketch3"="tri_length"
"D1@Tail" = "tail_length"
"tial_chord_length"= "vtail_mount"
"D1@VTail" = "tail_length" - 3
"D1@Sketch8"="vtail_mount" * cos( "vtail_mount_anglet")
"Nose_cone_length"= "fuse_length" / 2
"D1@Sketch17"="fuse_diam"/2
"D2@Sketch17" = "Nose_cone_length"
"wing_chord_length"= 5
"D1@Sketch19"="wing_chord_length"
"D2@Sketch19"=5
"D3@Sketch19"="wing_chord_length"
"D1@Boss-Extrude1"=("wingspan"/2)
"D1@Boss-Extrude2"=("fuse_diam"/2) - "wing_rotation_vert"
"wingspan"= 100